basePath: /api/v1
info:
  contact:
    email: helpdesk@gmail.com
    name: API Support
  description: Swagger API for Golang Project Blueprint.
  license:
    name: MIT
    url: https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
  title: Swagger Intro API
  version: "1.0"
paths:
  /v1/healthcheck:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Retrieves current status of Backend app
  /v1/movies:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Creates movie
  /v1/movies/{id}:
    get:
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Retrieves movie
swagger: "2.0"
